### ISSUE TITLE
keras手写体程序

### ISSUE THREAD

**Issue by lxj0276** [wepe/MachineLearning#10]
我运行的时候弹出这个错误信息，是怎么回事
Traceback (most recent call last):
  File "G:/MyCode/mmnist/keras_usage/cnn.py", line 85, in <module>
    sgd = SGD(l2=0.1,lr=0.05, decay=1e-6, momentum=0.9, nesterov=True)
  File "D:\Anaconda2\lib\site-packages\keras-1.0.3-py2.7.egg\keras\optimizers.py", line 117, in __init__
    super(SGD, self).__init__(**kwargs)
  File "D:\Anaconda2\lib\site-packages\keras-1.0.3-py2.7.egg\keras\optimizers.py", line 36, in __init__
    'passed to optimizer: ' + str(k))
Exception: Unexpected keyword argument passed to optimizer: l2

**Comment by CorcovadoMing** [comment]
@lxj0276 

FYI http://keras.io/optimizers/
There are no l2 parameter for SGD in newer Keras version
Maybe you should remove the l2 option in the function call

**Comment by lxj0276** [comment]
@CorcovadoMing 好的，谢谢啦，看来新版接口有变化

**Comment by younfor** [comment]
l2那个参数去掉就可以了
